import { ConfigBundle } from "./types.js";

export const DEFAULT_CONFIG: ConfigBundle = {
  weights: {
    businessRelevance: 0.34,
    unblockValue: 0.22,
    mergeReadiness: 0.18,
    effortReviewCost: 0.12,
    stalenessSignal: 0.09,
    communityValue: 0.05,
  },
  repoWeights: {},
  affiliationMap: {},
  lowHangingThresholds: {
    maxChangedLines: 80,
    maxFilesChanged: 4,
    maxReviewComments: 3,
    minAgeDays: 5,
  },
  labelRules: {
    businessLabels: [
      "release-blocker",
      "release",
      "customer",
      "support",
      "security",
      "regression",
      "compatibility",
      "compat",
      "urgent",
      "breaking-change",
    ],
    unblockLabels: [
      "blocker",
      "blocked",
      "compatibility",
      "release",
      "dependencies",
      "dependency",
      "migration",
      "upgrade",
      "unblock",
    ],
    maintenanceLabels: [
      "dependencies",
      "maintenance",
      "housekeeping",
      "ci",
      "workflow",
      "automation",
      "chore",
      "github-actions",
      "codeowners",
      "devcontainer",
      "lint",
      "formatting",
    ],
    quickWinLabels: [
      "docs",
      "documentation",
      "typo",
      "test",
      "tests",
      "bug",
      "bugfix",
      "regression",
      "compat",
      "small fix",
    ],
    customerLabels: ["customer", "support", "field", "solutions", "success"],
  },
  codeJamThresholds: {
    pickNextMinScore: 5.4,
    pickNextFloorScore: 4.8,
    pickNextTargetCount: 3,
    pickNextFallbackMergeReadinessMin: 8,
    pickNextFallbackEffortMin: 7,
    quickWinMinScore: 4.8,
    importantButHeavyBusinessScore: 6.0,
    importantButHeavyEffortMax: 4.5,
    highScoreThreshold: 6.0,
    stalePrAgeDays: 45,
    stalePrIdleDays: 21,
  },
};

export const GITHUB_API_URL = "https://api.github.com";
